# Generated by Django 4.2.16 on 2024-11-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetails',
            name='customerID',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='slug',
            field=models.IntegerField(unique=True),
        ),
    ]
