# Generated by Django 4.2.16 on 2024-12-08 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.IntegerField(primary_key=True, serialize=False)),
                ('hire_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_number', models.IntegerField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.RemoveField(
            model_name='customerdetail',
            name='author',
        ),
        migrations.RemoveField(
            model_name='customerdetail',
            name='content',
        ),
        migrations.RemoveField(
            model_name='customerdetail',
            name='id',
        ),
        migrations.RemoveField(
            model_name='customerdetail',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='customerdetail',
            name='status',
        ),
        migrations.RemoveField(
            model_name='customerdetail',
            name='title',
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='customer_id',
            field=models.IntegerField(default=69, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
