# Generated by Django 4.2.16 on 2024-12-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_staff_transaction_remove_customerdetail_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='car_registration',
            field=models.CharField(default='test', max_length=20),
            preserve_default=False,
        ),
    ]
