# Generated by Django 4.2.16 on 2024-12-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_transaction_car_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetail',
            name='email',
            field=models.EmailField(default='test', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='first_name',
            field=models.TextField(default='test', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerdetail',
            name='second_name',
            field=models.TextField(default='test', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='email',
            field=models.EmailField(default='test', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='first_name',
            field=models.TextField(default='test', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='position',
            field=models.TextField(default='test', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='second_name',
            field=models.TextField(default='test', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.TextField(default='test', max_length=20),
            preserve_default=False,
        ),
    ]
