# Generated by Django 4.2.16 on 2024-12-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_customerdetail_email_customerdetail_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetail',
            name='customer_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='email',
            field=models.EmailField(max_length=60),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='first_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='second_name',
            field=models.CharField(max_length=25),
        ),
    ]
