# Generated by Django 4.2.16 on 2024-12-10 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_alter_customerdetail_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetail',
            name='updated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='staff_idiot', to='sale.staff'),
            preserve_default=False,
        ),
    ]
