# Generated by Django 4.2.16 on 2024-12-10 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0006_customerdetail_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetail',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='updated_by_who', to='sale.staff'),
        ),
    ]
