# Generated by Django 4.2.16 on 2024-12-10 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0009_alter_staff_email_alter_staff_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='customer_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='customer_id_transaction', to='sale.customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='car_registration',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_number',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(default='sale', max_length=8),
        ),
    ]
