# Generated by Django 4.2.16 on 2024-12-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0010_transaction_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('sale', 'SALE'), ('purchase', 'PURCHASE')], default='sale', max_length=8),
        ),
    ]
