# Generated by Django 4.2.16 on 2024-12-22 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0015_alter_transaction_customer_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
